version: "3.9"

services:
  php:
    image: php:8.3-fpm
    container_name: technopay_php
    volumes:
      - /var/www/html/technopay:/var/www/html/technopay
    networks:
      - technopay_network

  nginx:
    image: nginx:latest
    container_name: technopay_nginx
    ports:
      - "8000:80"
    volumes:
      - /var/www/html/technopay:/var/www/html/technopay
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - technopay_network

  db:
    image: mysql:8.0
    container_name: technopay_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: technopay
      MYSQL_USER: technopay_user
      MYSQL_PASSWORD: technopay_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - technopay_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: technopay_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: technopay_user
      PMA_PASSWORD: technopay_pass
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - technopay_network

volumes:
  db_data:

networks:
  technopay_network:
    driver: bridge

